/** @jsxImportSource @emotion/react */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { css } from "@emotion/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Playgruond Next.js!</h1>

        <p className={styles.description}>
          This website is bootstrapped with{" "}
          <a
            css={css`
              &:is(:active, :focus, :hover) {
                text-decoration: underline !important;
                color: #0070f3 !important;
              }
            `}
            href="https://nextjs.org/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Next.js
          </a>{" "}
          +{" "}
          <a
            css={css`
              &:is(:active, :focus, :hover) {
                text-decoration: underline !important;
                color: #0070f3 !important;
              }
            `}
            href="https://mui.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Material UI 5
          </a>
          <br />
          Try explore some random features in here!!
        </p>

        <div className={styles.grid}>
          <Link href="/random-arithmetic" className={styles.card}>
            <h2>Random-Arithmetic &rarr;</h2>
            <p>
              Wanna play some game of arithmetic question? <br />
              <strong>Click here!</strong>
            </p>
          </Link>

          <Link href="/todos" className={styles.card}>
            <h2>Todos &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Link>

          <Link
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Link>

          <Link
            target="_blank"
            rel="noopener noreferrer"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
};

export default Home;
